version: "3.9"

services:
  screepsdocker:
    build:
      context: .
      args:
        - steam_api_key
    ports:
      - "21025:21025"
      - "21026:21026"
    volumes:
      - screeps-data-volume:/screeps-data
volumes:
  screeps-data-volume: